### ISSUE TITLE
Seem to have lost the ability to get the creation time

### ISSUE THREAD

**Issue by nlfiedler** [alfg/mp4rs#20]
In particular, reading the creation time from the mvhd of the moov part. All of the previous API in 0.4 is gone and the 0.5 version does not seem to have the same operations any more.

**Comment by alfg** [comment]
Hey @nlfiedler, 

Sorry about that. There were lots of refactoring and changes around the interface just recently. It seems the `ftyp` and `moov` boxes were just left private. I'll fix and publish a new version soon and with an updated README.md.

Thanks!

**Comment by alfg** [comment]
Check out the latest in `master`. I updated the README example and made `ftyp` and `moov` public, so you can access the child box info. I'll publish soon if all is good.

**Comment by nlfiedler** [comment]
Terrific, thank you for responding so quickly.

**Comment by alfg** [comment]
`0.5.1` crate is published.
