### ISSUE TITLE
A missing ESDS box is now treated as an error, but why?

### ISSUE THREAD

**Issue by nlfiedler** [alfg/mp4rs#22]
Updated to the 0.5.1 release and one of my tests are failing because the test file is missing the ESDS box. The result is an error of type `InvalidData` with the message "esds not found". The 0.4 release did not treat this condition as an error (or maybe that version never looked for this box type before), but now the 0.5.1 release is failing for me on some files because this box is missing. Is that really an error condition?

**Comment by alfg** [comment]
Fixed on #23. Also updated the mp4info example.

**Comment by nlfiedler** [comment]
Terrific, thank you.
