### ISSUE TITLE
Q: how should unknown boxes be handled?

### ISSUE THREAD

**Issue by nlfiedler** [alfg/mp4rs#3]
First, thank you for writing this and making it available. I'm hoping to use it to get the creation time from mp4 files, but I'm running into an issue. It seems that the files produced by iOS contain a box that this crate does not recognize. When that happens, it `break`s out of the loop in `read_boxes()` and subsequently misses reading the other boxes (in particular the `moov` box that has the creation time).

My question is, what would be the right thing to do? Just set `start` to `size - HEADER_SIZE` and carry on (except when `size` is zero, of course), or something else? I made that change locally and it was able to carry on and find a `moov` box, which is promising.

By the way, the box type in question was a "wide" box. Not quite sure what that is.

P.S. If this approach sounds reasonable, I can submit a pull request.

**Comment by alfg** [comment]
Hi @nlfiedler, 

Thanks for catching this. I'm not exactly sure what the `wide` box is used for, but I think your approach is reasonable. I do something similar on my Golang implementation at: https://github.com/alfg/mp4/blob/master/atom/box.go#L42 where I just move on to the `mdat` or `moov` box.

A PR would be great!

**Comment by alfg** [comment]
Fixed on https://github.com/alfg/mp4rs/pull/4. Thanks!
