### ISSUE TITLE
Some box fields are larger in version 1 than version 0.

### ISSUE THREAD

**Issue by nlfiedler** [alfg/mp4rs#6]
I have yet to find a video that is using version 1 boxes, but I came across the fact that several fields (e.g. creation time) are double the size if the box is version 1 instead of version 0. I want to address this, but first I want to find a spec to make sure I'm not missing anything. So far I found creation time, modification time, and duration in the mvhd, tkhd, and mdhd boxes.

**Comment by alfg** [comment]
Good point. I haven't added much support for versioning yet, but open to PRs.

**Comment by alfg** [comment]
Closing as box versions support was added as of `0.5.0`, including `mvhd`, `tkhd` and `mdhd` boxes.
